remote_theme: "poole/hyde"
title: Ten o programowaniu w C#
header_pages:
  - about.md
author: Piotr Cieślik
email: kontakt@piotrcieslik.pl
google_analytics: UA-160663764-1
github_username: piotr-cieslik
